// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/admin/createPublicCategory": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员模块"
                ],
                "summary": "创建公共知识库分类",
                "parameters": [
                    {
                        "description": "params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.CreateCategoryReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "resp",
                        "schema": {
                            "$ref": "#/definitions/v1.Response"
                        }
                    }
                }
            }
        },
        "/v1/admin/createPublicKB": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员模块"
                ],
                "summary": "创建公共知识库",
                "parameters": [
                    {
                        "description": "params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.CreateKBRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.CreateKBResp"
                        }
                    }
                }
            }
        },
        "/v1/admin/deletePublicCategory": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员模块"
                ],
                "summary": "删除公共知识库分类",
                "parameters": [
                    {
                        "description": "params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.DeleteCategoryReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.Response"
                        }
                    }
                }
            }
        },
        "/v1/admin/deletePublicKB": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员模块"
                ],
                "summary": "删除公共知识库",
                "parameters": [
                    {
                        "description": "params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.DeleteKBReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.Response"
                        }
                    }
                }
            }
        },
        "/v1/admin/updatePublicCategory": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员模块"
                ],
                "summary": "修改公共知识库分类",
                "parameters": [
                    {
                        "description": "params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.UpdateCategoryReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.Response"
                        }
                    }
                }
            }
        },
        "/v1/admin/updatePublicKB": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理员模块"
                ],
                "summary": "修改公共知识库",
                "parameters": [
                    {
                        "description": "params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.UpdateKBNameReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.Response"
                        }
                    }
                }
            }
        },
        "/v1/article/DeleteArticle": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文章模块"
                ],
                "summary": "删除文章",
                "parameters": [
                    {
                        "description": "params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.DeleteArticleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.DeleteArticleResponseData"
                        }
                    }
                }
            }
        },
        "/v1/article/DeleteArticleList": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文章模块"
                ],
                "summary": "批量删除文章",
                "parameters": [
                    {
                        "description": "params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.DelArticleListReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.DeleteArticleResponseData"
                        }
                    }
                }
            }
        },
        "/v1/article/UpdateArticle": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文章模块"
                ],
                "summary": "修改文章内容",
                "parameters": [
                    {
                        "description": "params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.UpdateArticleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.ArticleData"
                        }
                    }
                }
            }
        },
        "/v1/article/createArticle": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文章模块"
                ],
                "summary": "新建文章",
                "parameters": [
                    {
                        "description": "params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.CreateArticleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.CreateArticleResponseData"
                        }
                    }
                }
            }
        },
        "/v1/article/getArticle": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文章模块"
                ],
                "summary": "获取文章详细",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Article ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.ArticleData"
                        }
                    }
                }
            }
        },
        "/v1/article/getArticleListByEs": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文章模块"
                ],
                "summary": "es文章查询",
                "parameters": [
                    {
                        "description": "params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.GetArticleListByEsReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.SearchArticleResp"
                        }
                    }
                }
            }
        },
        "/v1/article/getUserArticleList": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文章模块"
                ],
                "summary": "获取个人文章列表",
                "parameters": [
                    {
                        "description": "params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.GetUserArticleListReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.ArticleList"
                        }
                    }
                }
            }
        },
        "/v1/getCaptcha": {
            "get": {
                "description": "获取验证码生成所需的ID和图片URL",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块"
                ],
                "summary": "获取验证码",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.CaptchaResponseData"
                        }
                    }
                }
            }
        },
        "/v1/knowledgeBase/createCategory": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "知识库模块"
                ],
                "summary": "新建知识库分类",
                "parameters": [
                    {
                        "description": "params",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.CreateCategoryReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.Response"
                        }
                    }
                }
            }
        },
        "/v1/knowledgeBase/createKB": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "知识库模块"
                ],
                "summary": "新建团队知识库",
                "parameters": [
                    {
                        "description": "params",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.CreateKBRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.CreateKBResp"
                        }
                    }
                }
            }
        },
        "/v1/knowledgeBase/deleteCategory": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "知识库模块"
                ],
                "summary": "删除知识库分类",
                "parameters": [
                    {
                        "description": "params",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.DeleteCategoryReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.Response"
                        }
                    }
                }
            }
        },
        "/v1/knowledgeBase/deleteKB": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "知识库模块"
                ],
                "summary": "删除知识库",
                "parameters": [
                    {
                        "description": "params",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.DeleteKBReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.Response"
                        }
                    }
                }
            }
        },
        "/v1/knowledgeBase/getCategoryListByKB": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "知识库模块"
                ],
                "summary": "获取知识库分类列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "知识库ID",
                        "name": "kb_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.CategoryData"
                        }
                    }
                }
            }
        },
        "/v1/knowledgeBase/getKBInfo": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "知识库模块"
                ],
                "summary": "获取知识库信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "知识库ID",
                        "name": "kb_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.GetKBInfoResp"
                        }
                    }
                }
            }
        },
        "/v1/knowledgeBase/getKBListByTeamId": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "知识库模块"
                ],
                "summary": "获取团队知识库列表",
                "parameters": [
                    {
                        "description": "params",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.GetKBListByTeamIdReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.GetKBListByTeamIdResp"
                        }
                    }
                }
            }
        },
        "/v1/knowledgeBase/getKBListByType": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "知识库模块"
                ],
                "summary": "获取知识库列表(私人知识库、公共知识库)",
                "parameters": [
                    {
                        "description": "params",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.GetKBListByTypeReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.KBList"
                        }
                    }
                }
            }
        },
        "/v1/knowledgeBase/updateCategory": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "知识库模块"
                ],
                "summary": "更新知识库分类",
                "parameters": [
                    {
                        "description": "params",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.UpdateCategoryReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.Response"
                        }
                    }
                }
            }
        },
        "/v1/knowledgeBase/updateKBName": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "知识库模块"
                ],
                "summary": "更新知识库名称",
                "parameters": [
                    {
                        "description": "params",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.UpdateKBNameReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.Response"
                        }
                    }
                }
            }
        },
        "/v1/passwordLogin": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块"
                ],
                "summary": "账号密码登录",
                "parameters": [
                    {
                        "description": "params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.PasswordLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.LoginResponseData"
                        }
                    }
                }
            }
        },
        "/v1/register": {
            "post": {
                "description": "目前只支持邮箱登录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "description": "params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.Response"
                        }
                    }
                }
            }
        },
        "/v1/team/addTeamMember": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "团队模块"
                ],
                "summary": "添加团队成员",
                "parameters": [
                    {
                        "description": "params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.AddTeamMemberReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.Response"
                        }
                    }
                }
            }
        },
        "/v1/team/createTeam": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "团队模块"
                ],
                "summary": "新建团队",
                "parameters": [
                    {
                        "description": "params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.CreateTeamRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.CreateTeamResp"
                        }
                    }
                }
            }
        },
        "/v1/team/deleteTeam": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "团队模块"
                ],
                "summary": "删除团队",
                "parameters": [
                    {
                        "description": "params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.DeleteTeamRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.Response"
                        }
                    }
                }
            }
        },
        "/v1/team/deleteTeamMember": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "团队模块"
                ],
                "summary": "删除团队成员",
                "parameters": [
                    {
                        "description": "params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.DeleteTeamMemberReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.Response"
                        }
                    }
                }
            }
        },
        "/v1/team/getTeamInfo": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "团队模块"
                ],
                "summary": "获取团队详细",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Team ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.GetTeamInfoResp"
                        }
                    }
                }
            }
        },
        "/v1/team/getTeamList": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "团队模块"
                ],
                "summary": "获取团队列表",
                "parameters": [
                    {
                        "description": "params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.GetTeamListReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.GetTeamListResp"
                        }
                    }
                }
            }
        },
        "/v1/team/getTeamMemberList": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "团队模块"
                ],
                "summary": "获取团队成员列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Team ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.GetTeamMemberListResp"
                        }
                    }
                }
            }
        },
        "/v1/team/getUserTeamList": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "团队模块"
                ],
                "summary": "获取个人团队列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page Index",
                        "name": "pageIndex",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page Size",
                        "name": "pageSize",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.GetUserTeamListResp"
                        }
                    }
                }
            }
        },
        "/v1/team/quitTeam": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "团队模块"
                ],
                "summary": "退出团队",
                "parameters": [
                    {
                        "description": "params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.QuitTeamReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.Response"
                        }
                    }
                }
            }
        },
        "/v1/team/updateTeam": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "团队模块"
                ],
                "summary": "更新团队",
                "parameters": [
                    {
                        "description": "params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.UpdateTeamRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.Response"
                        }
                    }
                }
            }
        },
        "/v1/team/updateTeamMemberRole": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "团队模块"
                ],
                "summary": "更新团队成员角色",
                "parameters": [
                    {
                        "description": "params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.UpdateTeamMemberRoleReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.Response"
                        }
                    }
                }
            }
        },
        "/v1/user/cancel": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块"
                ],
                "summary": "注销用户",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.Response"
                        }
                    }
                }
            }
        },
        "/v1/user/getCollege": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块"
                ],
                "summary": "获取学院信息",
                "parameters": [
                    {
                        "description": "params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.GetCollegeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.CollegeResponseData"
                        }
                    }
                }
            }
        },
        "/v1/user/getCollegeList": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块"
                ],
                "summary": "获取学院列表",
                "responses": {
                    "200": {
                        "description": "返回学院信息列表",
                        "schema": {
                            "$ref": "#/definitions/v1.GetCollegeListDataResponse"
                        }
                    }
                }
            }
        },
        "/v1/user/getUserInfo": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块"
                ],
                "summary": "获取用户信息",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.GetUserInfoResponseData"
                        }
                    }
                }
            }
        },
        "/v1/user/logout": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块"
                ],
                "summary": "退出用户",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.Response"
                        }
                    }
                }
            }
        },
        "/v1/user/updateProfile": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块"
                ],
                "summary": "修改用户信息",
                "parameters": [
                    {
                        "description": "params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.UpdateProfileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.Response"
                        }
                    }
                }
            }
        },
        "/v1/user/userAuth": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块"
                ],
                "summary": "用户认证",
                "parameters": [
                    {
                        "description": "params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.UserAuthRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "v1.AddTeamMemberReq": {
            "type": "object",
            "properties": {
                "member_id": {
                    "description": "成员ID",
                    "type": "string"
                },
                "role_type": {
                    "description": "角色类型",
                    "type": "string"
                },
                "team_id": {
                    "description": "团队ID",
                    "type": "integer"
                }
            }
        },
        "v1.ArticleData": {
            "type": "object",
            "properties": {
                "article_id": {
                    "description": "文章id",
                    "type": "integer"
                },
                "author": {
                    "description": "作者",
                    "type": "string"
                },
                "category": {
                    "description": "文章分类",
                    "type": "string"
                },
                "category_id": {
                    "description": "文章分类ID",
                    "type": "integer"
                },
                "comment_disabled": {
                    "description": "是否禁用评论",
                    "type": "boolean"
                },
                "content": {
                    "description": "文章内容",
                    "type": "string"
                },
                "content_short": {
                    "description": "文章摘要",
                    "type": "string"
                },
                "created_at": {
                    "description": "文章创建时间",
                    "type": "string"
                },
                "importance": {
                    "description": "文章重要性",
                    "type": "integer"
                },
                "kb_id": {
                    "description": "知识库ID",
                    "type": "integer"
                },
                "kb_name": {
                    "description": "知识库名称",
                    "type": "string"
                },
                "source_uri": {
                    "description": "文章外链",
                    "type": "string"
                },
                "status": {
                    "description": "文章状态",
                    "type": "integer"
                },
                "title": {
                    "description": "文章标题",
                    "type": "string"
                },
                "update_at": {
                    "description": "文章更新时间",
                    "type": "string"
                },
                "uploaded_files": {
                    "description": "上传的文件列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.FileUpload"
                    }
                }
            }
        },
        "v1.ArticleList": {
            "type": "object",
            "properties": {
                "articleDataList": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.ArticleData"
                    }
                },
                "page_index": {
                    "description": "当前页码",
                    "type": "integer"
                },
                "page_size": {
                    "description": "每页大小",
                    "type": "integer"
                },
                "total_count": {
                    "description": "总记录数",
                    "type": "integer"
                }
            }
        },
        "v1.ArticleSearchInfo": {
            "type": "object",
            "properties": {
                "article_id": {
                    "type": "integer"
                },
                "author": {
                    "type": "string"
                },
                "category": {
                    "type": "string"
                },
                "comment_disabled": {
                    "type": "boolean"
                },
                "content": {
                    "type": "string"
                },
                "content_short": {
                    "type": "string"
                },
                "created_at": {
                    "description": "使用 sql.NullTime",
                    "type": "string"
                },
                "importance": {
                    "type": "integer"
                },
                "score": {
                    "description": "评分（例如：基于ES的相关度评分）",
                    "type": "number"
                },
                "source_uri": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "description": "使用 sql.NullTime",
                    "type": "string"
                },
                "uploaded_file": {
                    "type": "boolean"
                }
            }
        },
        "v1.CaptchaResponseData": {
            "type": "object",
            "properties": {
                "Captcha_base64": {
                    "type": "string"
                },
                "captcha_id": {
                    "type": "string"
                }
            }
        },
        "v1.CategoryData": {
            "type": "object",
            "properties": {
                "CategoryList": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/vo.CategoryView"
                    }
                }
            }
        },
        "v1.CollegeResponseData": {
            "type": "object",
            "properties": {
                "collegeId": {
                    "type": "integer"
                },
                "collegeName": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                }
            }
        },
        "v1.CreateArticleRequest": {
            "type": "object",
            "required": [
                "article_id",
                "content",
                "title"
            ],
            "properties": {
                "article_id": {
                    "description": "作者ID",
                    "type": "string"
                },
                "category_id": {
                    "description": "文章分类ID",
                    "type": "integer"
                },
                "comment_disabled": {
                    "description": "是否禁用评论",
                    "type": "boolean"
                },
                "content": {
                    "description": "文章内容",
                    "type": "string"
                },
                "content_short": {
                    "description": "文章摘要",
                    "type": "string"
                },
                "importance": {
                    "description": "文章重要性",
                    "type": "integer"
                },
                "kb_id": {
                    "description": "知识库ID",
                    "type": "integer"
                },
                "sourceu_ri": {
                    "description": "文章外链",
                    "type": "string"
                },
                "title": {
                    "description": "文章标题",
                    "type": "string"
                },
                "uploaded_files": {
                    "description": "上传的文件列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.FileUpload"
                    }
                }
            }
        },
        "v1.CreateArticleResponseData": {
            "type": "object",
            "properties": {
                "article_id": {
                    "description": "文章ID",
                    "type": "integer"
                }
            }
        },
        "v1.CreateCategoryReq": {
            "type": "object",
            "required": [
                "category_name",
                "kb_id"
            ],
            "properties": {
                "category_name": {
                    "type": "string"
                },
                "kb_id": {
                    "type": "integer"
                },
                "parent_id": {
                    "type": "integer"
                }
            }
        },
        "v1.CreateKBRequest": {
            "type": "object",
            "required": [
                "name",
                "team_id"
            ],
            "properties": {
                "name": {
                    "type": "string"
                },
                "team_id": {
                    "type": "integer"
                }
            }
        },
        "v1.CreateKBResp": {
            "type": "object",
            "properties": {
                "kb_id": {
                    "type": "integer"
                }
            }
        },
        "v1.CreateTeamRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "description": "描述",
                    "type": "string"
                },
                "team_name": {
                    "description": "团队名",
                    "type": "string"
                }
            }
        },
        "v1.CreateTeamResp": {
            "type": "object",
            "properties": {
                "team_id": {
                    "description": "团队ID",
                    "type": "integer"
                }
            }
        },
        "v1.DelArticleListReq": {
            "type": "object",
            "properties": {
                "article_id_List": {
                    "description": "文章ID列表",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "v1.DeleteArticleRequest": {
            "type": "object",
            "properties": {
                "article_id": {
                    "description": "文章ID",
                    "type": "integer"
                }
            }
        },
        "v1.DeleteArticleResponseData": {
            "type": "object",
            "properties": {
                "deleted_count": {
                    "description": "删除的文章数量",
                    "type": "integer"
                }
            }
        },
        "v1.DeleteCategoryReq": {
            "type": "object",
            "required": [
                "cid"
            ],
            "properties": {
                "cid": {
                    "type": "integer"
                }
            }
        },
        "v1.DeleteKBReq": {
            "type": "object",
            "required": [
                "kb_id"
            ],
            "properties": {
                "kb_id": {
                    "type": "integer"
                }
            }
        },
        "v1.DeleteTeamMemberReq": {
            "type": "object",
            "properties": {
                "member_id": {
                    "description": "成员ID",
                    "type": "string"
                },
                "team_id": {
                    "description": "团队ID",
                    "type": "integer"
                }
            }
        },
        "v1.DeleteTeamRequest": {
            "type": "object",
            "properties": {
                "team_id": {
                    "description": "团队ID",
                    "type": "integer"
                }
            }
        },
        "v1.FileUpload": {
            "type": "object",
            "properties": {
                "file_name": {
                    "description": "文件名",
                    "type": "string"
                },
                "file_url": {
                    "description": "文件URL",
                    "type": "string"
                }
            }
        },
        "v1.GetArticleListByEsReq": {
            "type": "object",
            "properties": {
                "advSearch": {
                    "description": "是否启用高级搜索",
                    "type": "boolean"
                },
                "categories": {
                    "description": "分类id，用于筛选",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "column": {
                    "description": "排序字段，通常是 \"_score\"",
                    "type": "string"
                },
                "content": {
                    "description": "搜索的内容关键词",
                    "type": "string"
                },
                "createTimeEnd": {
                    "description": "文章结束时间",
                    "type": "string"
                },
                "createTimeStart": {
                    "description": "文章创建时间",
                    "type": "string"
                },
                "importance": {
                    "description": "文章重要性",
                    "type": "string"
                },
                "keywords": {
                    "description": "搜索的关键字数组",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "order": {
                    "description": "排序方式，\"asc\" 或 \"desc\"",
                    "type": "string"
                },
                "page_index": {
                    "description": "当前页码",
                    "type": "integer"
                },
                "page_size": {
                    "description": "每页大小",
                    "type": "integer"
                },
                "phraseMatch": {
                    "description": "是否启用短语匹配",
                    "type": "boolean"
                },
                "title": {
                    "description": "搜索的标题",
                    "type": "string"
                }
            }
        },
        "v1.GetCollegeListDataResponse": {
            "type": "object",
            "properties": {
                "collegeList": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.CollegeResponseData"
                    }
                }
            }
        },
        "v1.GetCollegeRequest": {
            "type": "object",
            "properties": {
                "collegeId": {
                    "type": "integer"
                }
            }
        },
        "v1.GetKBInfoResp": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "is_public": {
                    "type": "boolean"
                },
                "kb_id": {
                    "type": "integer"
                },
                "kb_name": {
                    "type": "string"
                },
                "kb_type": {
                    "type": "string"
                },
                "team_id": {
                    "type": "integer"
                },
                "team_name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                },
                "user_name": {
                    "type": "string"
                }
            }
        },
        "v1.GetKBListByTeamIdReq": {
            "type": "object",
            "required": [
                "team_id"
            ],
            "properties": {
                "page_index": {
                    "description": "当前页码",
                    "type": "integer"
                },
                "page_size": {
                    "description": "每页大小",
                    "type": "integer"
                },
                "team_id": {
                    "type": "integer"
                }
            }
        },
        "v1.GetKBListByTeamIdResp": {
            "type": "object",
            "properties": {
                "kb_list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.GetKBInfoResp"
                    }
                },
                "page_index": {
                    "description": "当前页码",
                    "type": "integer"
                },
                "page_size": {
                    "description": "每页大小",
                    "type": "integer"
                },
                "total_count": {
                    "description": "总记录数",
                    "type": "integer"
                }
            }
        },
        "v1.GetKBListByTypeReq": {
            "type": "object",
            "properties": {
                "kb_type": {
                    "type": "string"
                }
            }
        },
        "v1.GetTeamInfoResp": {
            "type": "object",
            "properties": {
                "member": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.MemberData"
                    }
                },
                "team": {
                    "$ref": "#/definitions/v1.TeamData"
                }
            }
        },
        "v1.GetTeamListReq": {
            "type": "object",
            "properties": {
                "created_by": {
                    "description": "创建者ID",
                    "type": "string"
                },
                "page_index": {
                    "description": "当前页码",
                    "type": "integer"
                },
                "page_size": {
                    "description": "每页大小",
                    "type": "integer"
                },
                "team_name": {
                    "description": "团队名",
                    "type": "string"
                }
            }
        },
        "v1.GetTeamListResp": {
            "type": "object",
            "properties": {
                "page_index": {
                    "description": "当前页码",
                    "type": "integer"
                },
                "page_size": {
                    "description": "每页大小",
                    "type": "integer"
                },
                "team_list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.TeamData"
                    }
                },
                "total_count": {
                    "description": "总记录数",
                    "type": "integer"
                }
            }
        },
        "v1.GetTeamMemberListResp": {
            "type": "object",
            "properties": {
                "member_list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.MemberData"
                    }
                }
            }
        },
        "v1.GetUserArticleListReq": {
            "type": "object",
            "properties": {
                "CreatedEnd": {
                    "description": "文章结束时间",
                    "type": "string"
                },
                "categoryId": {
                    "description": "文章分类ID",
                    "type": "integer"
                },
                "createdAt": {
                    "description": "文章创建时间",
                    "type": "string"
                },
                "page_index": {
                    "description": "当前页码",
                    "type": "integer"
                },
                "page_size": {
                    "description": "每页大小",
                    "type": "integer"
                },
                "status": {
                    "description": "文章状态",
                    "type": "integer"
                },
                "title": {
                    "description": "文章标题",
                    "type": "string"
                }
            }
        },
        "v1.GetUserInfoResponseData": {
            "type": "object",
            "properties": {
                "college_id": {
                    "type": "integer"
                },
                "email": {
                    "type": "string"
                },
                "nick_name": {
                    "type": "string",
                    "example": "alan"
                },
                "phone": {
                    "type": "string",
                    "example": "10012239028"
                },
                "role_type": {
                    "type": "integer",
                    "example": 0
                },
                "student_id": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "v1.GetUserTeamListResp": {
            "type": "object",
            "properties": {
                "page_index": {
                    "description": "当前页码",
                    "type": "integer"
                },
                "page_size": {
                    "description": "每页大小",
                    "type": "integer"
                },
                "team_list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.TeamData"
                    }
                },
                "total_count": {
                    "description": "总记录数",
                    "type": "integer"
                }
            }
        },
        "v1.KBList": {
            "type": "object",
            "properties": {
                "kb_list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/vo.KbKnowledgeBaseView"
                    }
                }
            }
        },
        "v1.LoginResponseData": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                }
            }
        },
        "v1.MemberData": {
            "type": "object",
            "properties": {
                "join_time": {
                    "description": "加入时间",
                    "type": "string"
                },
                "member_id": {
                    "description": "成员ID",
                    "type": "integer"
                },
                "member_name": {
                    "description": "成员ID",
                    "type": "string"
                },
                "nick_name": {
                    "description": "成员昵称",
                    "type": "string"
                },
                "role_type": {
                    "description": "角色类型",
                    "type": "string"
                },
                "team_id": {
                    "description": "团队ID",
                    "type": "integer"
                },
                "update_time": {
                    "description": "更新时间",
                    "type": "string"
                }
            }
        },
        "v1.PasswordLoginRequest": {
            "type": "object",
            "required": [
                "captcha_answer",
                "captcha_id",
                "password",
                "phone"
            ],
            "properties": {
                "captcha_answer": {
                    "description": "验证码字段",
                    "type": "string"
                },
                "captcha_id": {
                    "description": "验证码ID字段",
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "example": "123456"
                },
                "phone": {
                    "type": "string",
                    "example": "10012239028"
                }
            }
        },
        "v1.QuitTeamReq": {
            "type": "object",
            "properties": {
                "team_id": {
                    "description": "团队ID",
                    "type": "integer"
                }
            }
        },
        "v1.RegisterRequest": {
            "type": "object",
            "required": [
                "captcha_answer",
                "captcha_id",
                "password",
                "phone"
            ],
            "properties": {
                "captcha_answer": {
                    "description": "验证码字段",
                    "type": "string"
                },
                "captcha_id": {
                    "description": "验证码ID字段",
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "example": "123456"
                },
                "phone": {
                    "type": "string",
                    "example": "10012239028"
                }
            }
        },
        "v1.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "v1.SearchArticleResp": {
            "type": "object",
            "properties": {
                "articles": {
                    "description": "文章列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.ArticleSearchInfo"
                    }
                },
                "page_index": {
                    "description": "当前页码",
                    "type": "integer"
                },
                "page_size": {
                    "description": "每页大小",
                    "type": "integer"
                },
                "total_count": {
                    "description": "总记录数",
                    "type": "integer"
                }
            }
        },
        "v1.TeamData": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "创建时间",
                    "type": "string"
                },
                "created_by": {
                    "description": "创建者ID",
                    "type": "string"
                },
                "description": {
                    "description": "描述",
                    "type": "string"
                },
                "team_id": {
                    "description": "团队ID",
                    "type": "integer"
                },
                "team_name": {
                    "description": "团队名",
                    "type": "string"
                },
                "updated_at": {
                    "description": "更新时间",
                    "type": "string"
                }
            }
        },
        "v1.UpdateArticleRequest": {
            "type": "object",
            "required": [
                "article_id",
                "content",
                "title"
            ],
            "properties": {
                "article_id": {
                    "description": "作者ID",
                    "type": "string"
                },
                "category_id": {
                    "description": "文章分类ID",
                    "type": "integer"
                },
                "comment_disabled": {
                    "description": "是否禁用评论",
                    "type": "boolean"
                },
                "content": {
                    "description": "文章内容",
                    "type": "string"
                },
                "content_short": {
                    "description": "文章摘要",
                    "type": "string"
                },
                "importance": {
                    "description": "文章重要性",
                    "type": "integer"
                },
                "kb_id": {
                    "description": "知识库ID",
                    "type": "integer"
                },
                "sourceu_ri": {
                    "description": "文章外链",
                    "type": "string"
                },
                "title": {
                    "description": "文章标题",
                    "type": "string"
                },
                "uploaded_files": {
                    "description": "上传的文件列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.FileUpload"
                    }
                }
            }
        },
        "v1.UpdateCategoryReq": {
            "type": "object",
            "required": [
                "category_name",
                "cid"
            ],
            "properties": {
                "category_name": {
                    "type": "string"
                },
                "cid": {
                    "type": "integer"
                }
            }
        },
        "v1.UpdateKBNameReq": {
            "type": "object",
            "required": [
                "kb_id",
                "name"
            ],
            "properties": {
                "kb_id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "v1.UpdateProfileRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "1234@gmail.com"
                },
                "nick_name": {
                    "type": "string",
                    "example": "alan"
                }
            }
        },
        "v1.UpdateTeamMemberRoleReq": {
            "type": "object",
            "properties": {
                "member_id": {
                    "description": "成员ID",
                    "type": "string"
                },
                "role_type": {
                    "description": "角色类型",
                    "type": "string"
                },
                "team_id": {
                    "description": "团队ID",
                    "type": "integer"
                }
            }
        },
        "v1.UpdateTeamRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "description": "描述",
                    "type": "string"
                },
                "team_id": {
                    "description": "团队ID",
                    "type": "integer"
                },
                "team_name": {
                    "description": "团队名",
                    "type": "string"
                }
            }
        },
        "v1.UserAuthRequest": {
            "type": "object",
            "properties": {
                "college_id": {
                    "type": "integer"
                },
                "remarks": {
                    "type": "string"
                },
                "student_id": {
                    "type": "string"
                }
            }
        },
        "vo.CategoryView": {
            "type": "object",
            "properties": {
                "categoryName": {
                    "description": "分类名",
                    "type": "string"
                },
                "children": {
                    "description": "子分类",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/vo.CategoryView"
                    }
                },
                "cid": {
                    "description": "分类ID",
                    "type": "integer"
                },
                "kbId": {
                    "description": "知识库ID",
                    "type": "integer"
                },
                "level": {
                    "description": "层级",
                    "type": "integer"
                },
                "parentId": {
                    "description": "父分类ID",
                    "type": "integer"
                }
            }
        },
        "vo.KbKnowledgeBaseView": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "type": "string"
                },
                "is_public": {
                    "type": "boolean"
                },
                "kb_id": {
                    "type": "integer"
                },
                "kb_name": {
                    "type": "string"
                },
                "kb_type": {
                    "description": "知识库类型：私人/公共/团队",
                    "type": "string"
                },
                "team_id": {
                    "description": "团队ID，可能为空",
                    "type": "integer"
                },
                "team_name": {
                    "description": "团队名称",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "description": "用户ID，可能为空（私人知识库）",
                    "type": "string"
                },
                "user_name": {
                    "description": "用户昵称",
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8000",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Nunu Example API",
	Description:      "This is a sample server celler server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
