definitions:
  v1.ArticleData:
    properties:
      articleId:
        description: 文章id
        type: integer
      author:
        description: 作者
        type: string
      category:
        description: 文章分类
        type: string
      commentDisabled:
        description: 是否禁用评论
        type: boolean
      content:
        description: 文章内容
        type: string
      contentShort:
        description: 文章摘要
        type: string
      createdAt:
        description: 文章创建时间
        type: string
      importance:
        description: 文章重要性
        type: integer
      sourceUri:
        description: 文章外链
        type: string
      status:
        description: 文章状态
        type: integer
      title:
        description: 文章标题
        type: string
      updateAt:
        description: 文章更新时间
        type: string
      uploadedFiles:
        description: 上传的文件列表
        items:
          $ref: '#/definitions/v1.FileUpload'
        type: array
      visibleRange:
        description: 可见范围
        type: string
    type: object
  v1.CaptchaResponseData:
    properties:
      CaptchaBase64:
        type: string
      captchaId:
        type: string
    type: object
  v1.CategoryData:
    properties:
      CategoryList:
        items:
          $ref: '#/definitions/vo.CategoryView'
        type: array
    type: object
  v1.CollegeResponseData:
    properties:
      collegeId:
        type: integer
      collegeName:
        type: string
      description:
        type: string
    type: object
  v1.CreateArticleRequest:
    properties:
      authorId:
        description: 作者ID
        type: string
      categoryId:
        description: 文章分类ID
        type: integer
      commentDisabled:
        description: 是否禁用评论
        type: boolean
      content:
        description: 文章内容
        type: string
      contentShort:
        description: 文章摘要
        type: string
      importance:
        description: 文章重要性
        type: integer
      sourceUri:
        description: 文章外链
        type: string
      title:
        description: 文章标题
        type: string
      uploadedFiles:
        description: 上传的文件列表
        items:
          $ref: '#/definitions/v1.FileUpload'
        type: array
      visibleRange:
        description: 可见范围
        type: string
    required:
    - authorId
    - content
    - title
    - visibleRange
    type: object
  v1.CreateArticleResponseData:
    properties:
      articleId:
        description: 文章ID
        type: integer
    type: object
  v1.DelArticleListReq:
    properties:
      articleIDList:
        description: 文章ID列表
        items:
          type: integer
        type: array
    type: object
  v1.DeleteArticleRequest:
    properties:
      articleId:
        description: 文章ID
        type: integer
      authorId:
        description: 作者ID
        type: string
    type: object
  v1.DeleteArticleResponseData:
    properties:
      deletedCount:
        description: 删除的文章数量
        type: integer
    type: object
  v1.FileUpload:
    properties:
      fileName:
        description: 文件名
        type: string
      fileUrl:
        description: 文件URL
        type: string
    type: object
  v1.GetArticleRequest:
    properties:
      articleId:
        description: 文章ID
        type: integer
    type: object
  v1.GetCollegeListDataResponse:
    properties:
      collegeList:
        items:
          $ref: '#/definitions/v1.CollegeResponseData'
        type: array
    type: object
  v1.GetCollegeRequest:
    properties:
      collegeId:
        type: integer
    type: object
  v1.GetUserInfoResponseData:
    properties:
      collegeId:
        type: integer
      email:
        type: string
      nickname:
        example: alan
        type: string
      phone:
        example: "10012239028"
        type: string
      roleType:
        example: 0
        type: integer
      studentId:
        type: string
      userId:
        type: string
    type: object
  v1.LoginResponseData:
    properties:
      accessToken:
        type: string
    type: object
  v1.PasswordLoginRequest:
    properties:
      captchaAnswer:
        description: 验证码字段
        type: string
      captchaId:
        description: 验证码ID字段
        type: string
      password:
        example: "123456"
        type: string
      phone:
        example: "10012239028"
        type: string
    required:
    - captchaAnswer
    - captchaId
    - password
    - phone
    type: object
  v1.RegisterRequest:
    properties:
      captchaAnswer:
        description: 验证码字段
        type: string
      captchaId:
        description: 验证码ID字段
        type: string
      password:
        example: "123456"
        type: string
      phone:
        example: "10012239028"
        type: string
    required:
    - captchaAnswer
    - captchaId
    - password
    - phone
    type: object
  v1.Response:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
  v1.UpdateArticleRequest:
    properties:
      articleId:
        description: 文章ID
        type: integer
      authorId:
        description: 作者ID
        type: string
      categoryId:
        description: 文章分类ID
        type: integer
      commentDisabled:
        description: 是否禁用评论
        type: boolean
      content:
        description: 文章内容
        type: string
      contentShort:
        description: 文章摘要
        type: string
      importance:
        description: 文章重要性
        type: integer
      sourceUri:
        description: 文章外链
        type: string
      title:
        description: 文章标题
        type: string
      uploadedFiles:
        description: 上传的文件列表
        items:
          $ref: '#/definitions/v1.FileUpload'
        type: array
      visibleRange:
        description: 可见范围
        type: string
    required:
    - authorId
    - content
    - title
    - visibleRange
    type: object
  v1.UpdateProfileRequest:
    properties:
      email:
        example: 1234@gmail.com
        type: string
      nickname:
        example: alan
        type: string
    type: object
  v1.UserAuthRequest:
    properties:
      collegeId:
        type: integer
      remarks:
        type: string
      studentId:
        type: string
    type: object
  vo.CategoryView:
    properties:
      categoryName:
        type: string
      children:
        items:
          $ref: '#/definitions/vo.CategoryView'
        type: array
      cid:
        type: integer
      level:
        type: integer
      parentId:
        type: integer
    type: object
host: localhost:8000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Nunu Example API
  version: 1.0.0
paths:
  /article/DeleteArticle:
    post:
      consumes:
      - application/json
      parameters:
      - description: params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/v1.DeleteArticleRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.DeleteArticleResponseData'
      security:
      - Bearer: []
      summary: 删除文章
      tags:
      - 文章模块
  /article/DeleteArticleList:
    post:
      consumes:
      - application/json
      parameters:
      - description: params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/v1.DelArticleListReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.DeleteArticleResponseData'
      security:
      - Bearer: []
      summary: 批量删除文章
      tags:
      - 文章模块
  /article/GetArticle:
    get:
      consumes:
      - application/json
      parameters:
      - description: params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/v1.GetArticleRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.ArticleData'
      security:
      - Bearer: []
      summary: 获取文章详细
      tags:
      - 文章模块
  /article/UpdateArticle:
    post:
      consumes:
      - application/json
      parameters:
      - description: params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/v1.UpdateArticleRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.ArticleData'
      security:
      - Bearer: []
      summary: 修改文章内容
      tags:
      - 文章模块
  /article/createArticle:
    post:
      consumes:
      - application/json
      parameters:
      - description: params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/v1.CreateArticleRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.CreateArticleResponseData'
      security:
      - Bearer: []
      summary: 新建文章
      tags:
      - 文章模块
  /article/getArticleCategory:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.CategoryData'
      security:
      - Bearer: []
      summary: 获取文章分组
      tags:
      - 文章模块
  /cancel:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.Response'
      security:
      - Bearer: []
      summary: 注销用户
      tags:
      - 用户模块
  /getCaptcha:
    get:
      consumes:
      - application/json
      description: 获取验证码生成所需的ID和图片URL
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.CaptchaResponseData'
      summary: 获取验证码
      tags:
      - 用户模块
  /passwordLogin:
    post:
      consumes:
      - application/json
      parameters:
      - description: params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/v1.PasswordLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.LoginResponseData'
      summary: 账号密码登录
      tags:
      - 用户模块
  /register:
    post:
      consumes:
      - application/json
      description: 目前只支持邮箱登录
      parameters:
      - description: params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/v1.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.Response'
      summary: 用户注册
      tags:
      - 用户模块
  /user/getCollege:
    get:
      consumes:
      - application/json
      parameters:
      - description: params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/v1.GetCollegeRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.CollegeResponseData'
      security:
      - Bearer: []
      summary: 获取学院信息
      tags:
      - 用户模块
  /user/getCollegeList:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: 返回学院信息列表
          schema:
            $ref: '#/definitions/v1.GetCollegeListDataResponse'
      security:
      - Bearer: []
      summary: 获取学院列表
      tags:
      - 用户模块
  /user/getUserInfo:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.GetUserInfoResponseData'
      security:
      - Bearer: []
      summary: 获取用户信息
      tags:
      - 用户模块
  /user/logout:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.Response'
      security:
      - Bearer: []
      summary: 退出用户
      tags:
      - 用户模块
  /user/updateProfile:
    post:
      consumes:
      - application/json
      parameters:
      - description: params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/v1.UpdateProfileRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.Response'
      security:
      - Bearer: []
      summary: 修改用户信息
      tags:
      - 用户模块
  /user/userAuth:
    post:
      consumes:
      - application/json
      parameters:
      - description: params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/v1.UserAuthRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.Response'
      security:
      - Bearer: []
      summary: 用户认证
      tags:
      - 用户模块
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
